CREATE TABLE TB_MENSAGEM_CHAMADO (
ID_MENSAGEM_CHAMADO     INTEGER,
ID_CHAMADO              INTEGER,
ID_USUARIO				INTEGER,
DS_MENSAGEM_CHAMADO     VARCHAR(200) DEFAULT 'AGUARDANDO RESPOSTA',
DT_ENVIO_MENSAGEM       DATE DEFAULT GETDATE(),

CONSTRAINT PK04_ID_MENSAGEM_CHAMADO     PRIMARY KEY (ID_MENSAGEM_CHAMADO),
CONSTRAINT FK04_ID_CHAMADO  FOREIGN KEY (ID_CHAMADO) REFERENCES TB_CHAMADO (ID_CHAMADO),
CONSTRAINT PK04_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)

);